---
title: "Enabling conditions for effective community based marine reserves in small scale fisheries"
author: "Juan Carlos Villaseñor-Derbez$^{1,*}$, Eréndira Aceves-Bueno$^{1,*}$, Alvin Suarez-Castillo$^{2}$, Stuart Fulton$^{2}$, Jorge Torre$^{2}$"
date: "$^{1}$Bren School of Environmental Science and Management, University of California, Santa Barbara, Santa Barbara, CA, USA. $^{2}$Comunidad y Biodiversidad A.C.,  Guaymas, Mexico"
output: pdf_document
---

# Abstract

Coastal marine ecosystems provide livelihoods for small-scale fishers and coastal communities around the world. However, overfishing and unsustainable fishing practices threaten the marine environment and jeopardize the wellbeing of coastal communities. A common approach to protect the environment and recover overexploited stocks is to implement no-take marine reserves (areas where all extractive activities are off-limits). In small-scale fisheries, these are sometimes implemented as community-based reserves, where a group of fishers collectively agree to close an area to fishing. While we know that reductions in fishing effort are followed by a series of ecological benefits (increased biomass, abundance, and species diversity), we do not fully understand how environmental and governance dynamics influence the conservation and fisheries benefits of community-based marine reserves. In this work, we evaluate the ecological outcomes of four reserves established by three coastal communities in temperate and tropical ecosystems of Mexico. By combining causal inference techniques with an operationalization of the social-ecological systems framework, we identify the environmental and social conditions that enable reserve effectiveness. Our results show a strong interaction between environmental variation and community organization, which influences reserve effectiveness. For example, the most effective reserve had strong governance structures accompanied with low environmental variability. Thus, even when a community is well organized (and reserves are well enforced), environmental variation can hinder the benefits of a reserve, and vice versa. Our results are particularly relevant under present changing climate conditions, as they can better inform management and decision making.

# How does this paper address the transdisciplinarity and/or transformation of small-scale fisheries?

Our methodological approach uses state-of-the-art econometric techniques to evaluate the causal effect of marine reserves on a series of ecological indicators, which enable us to control for spatiotemporal dynamics. By combining changes these with catch and revenues from associated fisheries, along with the social-ecological systems framework and information generated by the communities themselves through a large-scale citizen science program, we are able further identify the conditions that enable reserve effectiveness.

#What are the key messages in your paper about the future and/or sustainability of small-scale fisheries?

-	Reserve effectiveness can be better explained by analyzing the effect of both environmental variation and governance.
-	The benefits of community-based conservation can be diminished by environmental variation even in the presence of strong governance systems.
