---
title: "Efectividad de reservas marinas a nivel nacional"
subtitle: "Casos de estudio del Pacífico, Golfo de California, y Sistema Arrecifal Mesoamericano"
header-includes:
- \usepackage{setspace}
- \doublespacing
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    toc: yes
fontsize: 12pt
bibliography:
- exported-references.bib
- packages.bib
csl: huct.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
options(knitr.table.format = "latex")

windowsFonts(Times=windowsFont("TT Times New Roman"))

```

Juan Carlos Villaseñor-Derbez^1\*^, Stuart Fulton^2^, Jorge Torre^2^

^1^ Bren School of Environmental Science and Management, University of California Santa Barbara, Santa Barbara, California, United States

^2^ Comunidad y Biodiversidad A.C., Calle Isla del Peruano, Guaymas, Sonora, México


# Resumen ejecutivo

# Introducción

La sobrepesca y prácticas pesqueras no sostenibles son unas de las mayores amenazas para la conservación de los ecosistemas marinos del mundo [@halpern_2008-dK; @halpern_2017-Zi]. Esto es particularmente cierto para el caso de las pesquerías artesanales. La implementación de reservas marinas ( i.e. áreas donde la captura de una o más especies está prohibida) es una medida de manejo frecuentemente propuesta para recuperar stocks pesqueros e impulsar la productividad pesquera en aguas cercanas [@afflerbach_2014-HP; @krueck_2017-J1; @sala_2017-69]. Recientes trabajos han demostrado que también pueden mitigar y proveer amortiguamiento ante el cambio climático [@roberts_2017-J9], solve bycatch problems [@hastings_2017-sm] y en general, incrementar la biomasa, riqueza y densidades de organismos dentro de sus fronteras [@lester_2009-Ks; @giakoumi_2017-V2; @sala_2017-69].

En México, las reservas marinas han sido comúnmente establecidas como zonas núcleo dentro de Reservas de la Biósfera (RBs), administradas por la Comisión Nacional de Áreas Naturales Protegidas (CONANP). Al día de hoy, **41** RBs protegen una porción del ambiente marino en México. Sin embargo, solamente **27** de estas incluyen (pequeñas) zonas núcleo donde las actividades pesqueras están prohibidas. Aunque la CONANP ha hecho esfuerzos importantes por involucrar a los actores durante la implementación de las reservas, éste proceso aún se caracteriza por un proceso descendente, el cual conlleva a la falta de cumplimiento por parte de los actores. La escasez de recursos monetarios y humanos de la comisión limitan también el monitoreo y vigilancia de las reservas, limitando el desempeño de la reserva.

Buscando promover una alternativa con procesos ascendentes para implementar reservas marinas, las OSCs comenzaron a trabajar con comunidades pesqueras para establecer reservas comunitarias [@uribe_2010-u2] . Estas son comúnmente establecidas dentro de zonas de concesión, una forma de derechos de uso territoriales para pesquerías (TURF, en inglés). Al permitir a los pescadores diseñar sus propias reservas, una mayor proporción de la comunidad está de acuerdo con los perímetros establecidos, y por lo tanto los respetan [@gelcich_2015-Gw; @espinosaromero_2014-PY; @beger_2004-Y8] . Adicionalmente, los pescadores pueden implementar sus reservas por un periodo acordado (usualmente cinco años), después del cual la reserva puede ser abierta a la pesca. Esto provee a los pescadores con un sentido de confianza de que, en caso de ser necesario, aún tienen acceso a pescar esa zona[^1]. Las reservas son directamente vigiladas y monitoreadas por la comunidad, quienes comúnmente utilizan pequeñas embarcaciones (*e.g.* pangas) para patrullar la zona, o realizan avistamientos desde la costa en búsqueda de pescadores ilegales Aún así, las reservas comunitarias carecen de reconocimiento legal; por lo tanto, no hay forma de penalizar a los infractores.

[^1]: Hasta ahora, solamente una comunidad ha decidido abrir sur reservas a la pesca.

Sin embargo, en el 2014 una nueva norma [@nom049sagpesc_2014-V6] permite a los pescadores solicitar el establecimiento de reservas marinas bajo el nombre de “Zonas de refugio Pesquero” (ZRP). El manejo de las ZRP combina procesos ascendentes y descendentes al reconocer legalmente las reservas propuestas por las comunidades. Posterior a la revisión por parte de la Comisión Nacional de Acuacultura y Pesca (CONAPESCA) y la opinión técnica del Instituto Nacional de Acuacultura y Pesca (INAPESCA) las ZRP son establecidas por el periodo solicitado por los pescadores [^2] . El monitoreo y la vigilancia de las ZRP es típicamente llevado a cabo por la comunidad , con ayuda de OSCs locales. Hasta este cambio regulatorio, las reservas comunitarias no contaban con el soporte legal, y eran solamente reconocidas por la comunidad. Al día de hoy, existen **35** ZRP establecidas en el Pacífico, Golfo de California y Caribe Mexicano.

[^2]: Existen excepciones a esto, como la “Zona de Refugio Pesquero Golfo de Ulloa” y la “Zona de Refugio Pesquero Akumal”, creadas por CONAPESCA para cerrar la pesca y prevenir la captura incidental de tortugas marinas.

Aunque existen tres aproximaciones generales para implementar reservas marinas en México (*i.e.* Zonas núcleo dentro de AMP, reservas comunitarias y Zonas de Refugio Pesuqero), aún no comprendemos a fondo las características sociales que permiten su efectividad. La ciencia de reservas marinas se ha enfocado ampliamente en los efectos biológicos que estas tienen [@lester_2009-Ks; @giakoumi_2017-V2; @sala_2017-69; @afflerbach_2014-HP; @krueck_2017-J1]. Aunque el aspecto ecológico de las reservas es importante para su éxito, su efectividad también depende del estado socioeconómico y los sistemas de gobernanza de las comunidades pesqueras. La literatura indica que diferentes características influyen en el éxito de una reserva. En Palau, por ejemplo, la edad (*i.e.* tiempo de implementación), tamaño y hábitat contenido son características claves que determinan la efectividad [@friedlander_2017-oI]. Por otro lado, en el Mar Meditarráneo, @difranco_2016-Xw identifican que la procuración y vigilancia, presencia de un plan de manejo, participación de pescadores en el manejo, representación de pescadores en la toma de decisiones y promoción de la pesca sustentable son los cinco factores que incrementan la salud de los stocks, el ingreso a los pescadores, y se presenta una mayor aceptación social de las prácticas de manejo. En una aproximación global, @edgar_2014-UO encuentran que la procuración, edad, tamaño y aislamiento son determinantes de la efectividad de las reservas. Por lo tanto, observamos que las características que habilitan el éxito varían a través de regiones, y poco esfuerzo se ha hecho por comprender estas interacciones en México.

# Objetivos

El objetivo de este trabajo este trabajo es realizar una evaluación de la efectividad de reservas marinas en México, presentando resultados de cinco comunidades costeras como caso de estudio. Las comunidades utilizadas en este reporte se distribuyen a lo largo de la costa Pacífica de Baja Claifornia, el Golfo de California, y el Sistema Arrecifal Mesoamericano. Con el fin de obtener una visión holística del sistema, la evaluación se realizará tomando en cuenta indicadores biológicos, socioeconómicos y de gobernanza (**Referencia aqui**).

La evaluación de éstos cinco casos de estudios nos permitirá identificar patrones en los que características socioeconómicas y de gobernanza que se encuentran ligadas a la efectividad (biológica) de las reservas marinas evaluadas. Los patrones identificados podrán utilizarse para informar la toma de desiciones para la implementación de la red de reservas marinas en la Región de las Grandes Islas del Golfo de California.

# Materiales y Métodos

## Zonas de estudio

## Caraterísticas de las comunidades y reservas seleccionadas

## Análisis de datos

# Resultados

# Conclusiones

# Referencias