---
title: "Data Cleaning logbook"
author: "Juan Carlos Villaseñor-Derbez"
date: "last compilation: `r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(rfishbase)
  library(tidyverse)
})
```


# Ecological data

## Invertebrates

```{r}
invert <- read.csv(here::here("raw_data", "invert_data.csv"), strip.white = T, stringsAsFactors = F) %>% 
  janitor::clean_names() %>% 
  filter(comunidad %in% c("Isla Natividad", "Maria Elena", "Punta Herrero")) %>% 
  filter(!is.na(rc),
         rc %in% c("La Plana / Las Cuevas - La Dulce / Babencho",
                   "Cabezo - Cabezo (Control)",
                   "Manchon - Manchon (Control)",
                   "El Faro - El Faro (Control)")) %>% 
  filter(!(rc %in% c("El Faro - El Faro (Control)") & ano == 2012)) %>% 
  filter(abundancia > 0) %>% 
  group_by(comunidad, ano, rc, sitio, zona, transecto, generoespecie) %>% 
  summarize(abundancia = sum(abundancia)) %>% 
  ungroup() %>% 
  mutate(year = case_when(comunidad == "Isla Natividad" ~ ano - 2006,
                         comunidad == "Maria Elena" ~ ano - 2012,
                         TRUE ~ ano - 2013)) %>% 
  select(comunidad, ano, year, rc, sitio, zona, transecto, generoespecie, abundancia) %>% 
  arrange()
```

## Fish

### Species biology

```{r}
species_bio <- MPAtools::species_bio

needed_spp <- c("Kyphosus incisor",
                "Kyphosus sectatrix",
                "Pterois volitans",
                "Scarus guacamaia",
                "Chaetodon capistratus",
                "Chaetodon capistratus",
                "Chaetodon striatus",
                "Calamus pennatula")

FB_update <- rfishbase::length_weight(needed_spp, fields = c("a", "b")) %>% 
  select(GeneroEspecie = sciname, a, b) %>% 
  mutate(GeneroEspecie = case_when(GeneroEspecie %in% c("Kyphosus sectatrix", "Kyphosus incisor") ~ "Kyphosus",
                                   GeneroEspecie %in% c("Chaetodon capistratus", "Chaetodon striatus") ~ "Chaetodon",
                                   TRUE ~ GeneroEspecie)) %>% 
  group_by(GeneroEspecie) %>% 
  summarize_all(mean, na.rm = T) %>% 
  ungroup()

needed_genus <- c("Mycteroperca",
                  "Chromis",
                  "Stegastes",
                  "Haemulon",
                  "Acanthurus",
                  "Sebastes",
                  "Lutjanus",
                  "Scarus")

GenusLevelBio <- species_bio %>% 
  filter(Genus %in% needed_genus) %>%
  select(GeneroEspecie = Genus, a, b) %>% 
  group_by(GeneroEspecie) %>% 
  summarize_all(mean, na.rm = T) %>% 
  ungroup()

species_bio %<>%
  select(GeneroEspecie, a, b) %>% 
  rbind(FB_update) %>% 
  rbind(GenusLevelBio) %>% 
  janitor::clean_names()
```

### Clean data

```{r}
fish <- read.csv(here::here("raw_data", "fish_data.csv"), strip.white = T, stringsAsFactors = F) %>% 
  janitor::clean_names() %>% 
  filter(comunidad %in% c("Isla Natividad", "Maria Elena", "Punta Herrero")) %>% 
  filter(!is.na(rc),
         rc %in% c("La Plana / Las Cuevas - La Dulce / Babencho",
                   "Cabezo - Cabezo (Control)",
                   "Manchon - Manchon (Control)",
                   "El Faro - El Faro (Control)")) %>% 
  filter(!(rc %in% c("El Faro - El Faro (Control)") & ano == 2012)) %>% 
  filter(abundancia > 0) %>% 
  mutate(generoespecie = case_when(generoespecie == "Cephalopholis cruentatus" ~ "Cephalopholis cruentata",
                                   generoespecie == "Haemulon macrostomun" ~ "Haemulon macrostomum",
                                   generoespecie == "Xcochin spp" ~ "Balistes capriscus",
                                   generoespecie == "Pterois volitans/miles" ~ "Pterois volitans",
                                   generoespecie == "Mycteroperca spp" ~ "Mycteroperca",
                                   generoespecie == "Chromis spp" ~ "Chromis",
                                   generoespecie == "Damisela spp" ~ "Stegastes",
                                   generoespecie == "Haemulon spp" ~ "Haemulon",
                                   generoespecie == "Lancero spp" ~ "Acanthurus",
                                   generoespecie == "Kyphosus sectatrix/incisor" ~ "Kyphosus",
                                   generoespecie == "Sebastes spp" ~ "Sebastes",
                                   generoespecie == "Loro spp" ~ "Scarus",
                                   generoespecie == "Lutjanus spp" ~ "Lutjanus",
                                   generoespecie == "Mariposa spp" ~ "Chaetodon",
                                   generoespecie == "Pluma spp" ~ "Calamus pennatula",
                                   generoespecie == "Sparisoma aurolineatum" ~ "Sparisoma aurofrenatum",
                                   generoespecie == "Vieja spp" ~ "Bodianus rufus",
                                   TRUE ~ generoespecie)) %>% 
  left_join(species_bio, by = c("generoespecie")) %>% 
  group_by(comunidad, ano, rc, sitio, zona, transecto, generoespecie, talla, a,b) %>% 
  summarize(abundancia = sum(abundancia)) %>% 
  ungroup() %>% 
  mutate(year = case_when(comunidad == "Isla Natividad" ~ ano - 2006,
                         comunidad == "Maria Elena" ~ ano - 2012,
                         TRUE ~ ano - 2013)) %>% 
  select(comunidad, ano, year, rc, sitio, zona, transecto, generoespecie, talla, abundancia, a, b) %>% 
  arrange()
```

# Socioeconomic data

## CPI

```{r}
cpi <- read.csv(here::here("raw_data", "CPI.csv"), stringsAsFactors = F, strip.white = T)

cpi_2014 <- cpi$CPI[cpi$Ano == 2014]
```


## Landings and revenue

```{r}
conapesca <- readRDS(here::here("raw_data","conapesca.rds")) %>% 
  filter(UnidadEconomica %in% c("Scpp cozumel scl",
                                "Scpp jose maria azcorra scl",
                                "Scpp buzos y pescadores de la baja california scl")) %>% 
  filter(NombreComun %in% c("Langosta roja ent. fca.", "Langosta ent. fca.")) %>%
  group_by(UnidadEconomica, Ano, NombreComun) %>%
  summarize(PesoDesembarcado = sum(PesoDesembarcado), 
            PesoVivo = sum(PesoVivo),
            Valor = sum(Valor)) %>%
  filter(!(UnidadEconomica == "Scpp buzos y pescadores de la baja california scl" & NombreComun == "Langosta ent. fca.")) %>% 
  left_join(cpi, by = "Ano") %>% 
  mutate(Valor = Valor * (CPI / cpi_2014))
```


# Export all data

```{r}
write.csv(x = invert, file = here::here("data", "invertebrates.csv"), row.names = F)

write.csv(x = fish, file = here::here("data", "fish.csv"), row.names = F)

write.csv(x = conapesca, file = here::here("data", "conapesca.csv"))

```

