---
title: "Reviewer Report"
output: pdf_document
---

# Letter from the editor

- There are some rather loose statements in the ms, starting with the Abstract (see also Rev 1) where it is implied that a 'well-managed' fishery should result in no effect in a reserve. This is false. Most 'well-managed' fisheries aim to bring B0 to around 50% of unfished biomass, so reserves should on average contain double the density of fished areas. There is one unsubstantiated statement (line 81) of good enforcement, but could it not be just as likely that there is fishing activity in these reserves? Poaching is an equally valid explanation as any examine din the Discussion.

*That is correct, a reserve would contain higher density, biomass, and richness. We have corrected the abstract to reflect what we intended to say, which is that a well-managed fishery would not see increased catches by an additional intervention. We do not include explicit references in the abstract, but the discussion touches on this topic and cites Hilborn, Micheli and De Leo's paper that evaluates when MRs result in increased catches.*

*As for the unsubstantiated statement of good enforcement, it is unlikely that these reserves experience poaching. The reserves are implemented, managed, and monitored by the community themselves. We have expanded on this when we introduce the case studies.*

- As per Reviewer 1, much more clarity is needed in Methods. It is unclear what data are being tested and what the sampling design was, especially the spatial arrangement of controls. The modeling approach was also confusing to me - you have categorical responses so why 'multiple regression'? Your reporting indicates a log-linear model (especially the use of lambda) which is probably the most appropriate structure for fish data.

*We have expanded on the methods, especially by adding to the description of case studies (TURFs, reserve implementation process) and data collection methods to clarify what the sampling design is. We have also expanded on the regression model. It is a multiple linear regression because we incorporate more than one explanatory variable. The lambda that we report does not make reference to the lambda parameter in a Poisson distribution, but rather to the coefficient presented in Equations 1 and 2. We do not use a log-linear model that assumes a discrete poison distribution because our indicators are density (i.e. org / m^-2^) and biomass (Kg / m^-2^), which are continuous variables.*

- There is also some fairly lazy scholarship here: e.g. BACI designs originate in papers other than those cited on line 112-113, and were demonstrated in papers well before those in 114-115, and again in 133-134. The Moland et al. paper may not be a good example anyway since their sampling was spatially confounded. Discussion of spatial comparisons and before-after studies seems to imply nobody has ever used monitoring time series before. 
I am also confused by lines 250-252 where it is implied that this does study does not in fact have fished controls in the design.

*The observation that Moland's paper might have confounded estimates of reserve effectiveness is correct. Proximity of their reserve and control sites might imply a spillover effect from the reserves to the controls may occur, which would result in more conservative estimates of reserve effectiveness. While there is a long history of time series analyses in ecology, we cite Moland's paper because, to our knowledge, it is the first paper that estimated reserve effectiveness using a difference-in-differences approach. We have included references to older implementations of BACI in ecology, as well as the seminal econometric paper that introduces the Difference-in-Differences methodology.*

\clearpage

# Reviewer 1

This review focuses on the more substantial points, and I have not commented on minor issues.

### ABSTRACT

- I found the abstract somewhat misleading after reading the full ms because it implies that the findings include data on the level of support among fishing communities (L14), but this data is not presented in the results. In line with this the last sentence of the abstract seems to be speculation, and is not supported by evidence presented in the manuscript.

*A particular characteristic of Fish Refuges is that they are implemented with a pre-determined expiration date. Reserves are only re-implemented if the fishers decide to do so. We view this willingness to renew the reserves as a continued support. We have expanded in the description of the case studies and discussion to explain the reserve implementation process and why we think that these reserves continue to be supported. Furthermore, the work by Ayer et al., 2018 explicitly looked at the perceptions that these communities have about these reserves, and their findings support our statements. We have modified the last sentence of the manuscript to present a solid conclusion about the recommendations for the reserves we evaluate, but without speculating about fisher's perception of marine conservation.*

### INTRODUCTION

- The introduction is brief and not easy to follow. It could be usefully expanded to develop the argument for this study and demonstrate the novel elements. My suggestion would be to expand it to more clearly explain what TURFS are, and what benefits TURF-reserves are expected to deliver in comparison to TURFS or reserves alone.

- I found the introduction confusing in parts because some statements say there is little evidence around TURFs, while others seem to refer to documented benefits. There is quite a lot of switching between references to studies of TURFS, reserves, and TURF-reserves. A clearer explanation of the existing science would help convey the knowledge gap. One general issue is that there are several places in the ms where it was difficult to distinguish between theoretical/expected outcomes or relationships, and those supported by evidence from this or other studies – it would be helpful if the authors could clarify these areas.

- In the third paragraph it wasn't clear to me whether the authors see TURF-reserves as synonymous with community-based marine reserves, or if not what the differences are. As the authors note, who these rights are conferred and recognized by is an important consideration and needs further explanation. In line with this the authors should perhaps revisit the title, which refers to community-based marine reserves, but not to TURFs. 

- I suggest moving the specific details of Mexican TURFs to the case study section to provide context for the study sites, and focus on the broader issues in the introduction.

*The points raised above were amongst the most useful comments, and the fact that these were highlighted by both reviewers suggest that there was room for improvement. We have significantly expanded the introduction by including more background on TURFs, reserves, and TURF reserves. We have re-written some paragraphs to highlight the fact that TURF-reserve effectiveness has been proposed from theoretical and modelling work, but that no empirical evidence exists for reserves*

*We have also included a brief motivation for the study based on Mexican regulation, but moved the bulk of the case studies to the Methods section.*

### METHODS

- In the study area section more information would be useful on the wider context (some of this is in the introduction e.g. the TURF system in Mexico and governance arrangements for this system and the reserves within it).

*We have included more information on the wider context, touching on implementation processes and TURF history.*

- The claims that the communities are representative and that insights could be generalized to elsewhere in the world could be toned down. Some evidence that the communities share similarities with other fishing communities is useful, but the authors themselves suggest in the discussion that wide generalizations are not possible. 

*We have toned down the generalizations and made distinctions between our claims of when to generalize. Specifically, we meant to say that one may generalize our findings to other TURF-managed fisheries where community-based reserves are implemented. Further down in the discussion, we meant to say that no generalizations should be made to other Fish Refuges not implemented in TURF-managed fisheries. We believe that our current description and expanded introduction help make this more clear.*

- More information on data collection would help the reader to have greater confidence in the data and make the study more replicable – e.g. numbers of surveys/data points, location of control sites and counterfactuals, processes of site selection, etc. Some of this could be added to Table 1 (or perhaps to supplementary info?). 

*We have included more information on data collection as supplementary materials, where we show the number of transects for each site (reserve - control) and type of survey (invertebrate - fish). The process of site selection is presented in the methods, where we expanded the definition of our control sites (L142)*

- With regard to the evaluation of SES – it wasn't clear to me what the purpose of this evaluation was, and the data sources (and analysis of these) seemed sparse. There is little explanation of why these factors are important in relation to TURF-reserves, and only minimal reference to the original work that led to this framework.

*We have explicitly mentioned the objective of evaluating the SES in our methods section (L134), and further explained variable selection in L203.*

- My assumption is that the statistical analysis is appropriate to the data and questions. This is not really my area of expertise, though as someone who is reasonably conversant with statistical modelling I did find it difficult to follow the explanation of the analysis.

*We have expanded on the methods section and further explained the Difference-in-Differences method (L178). We have also included a reference to the main paper (Card and Krueger, 1994) where the DiD methodology was first introduced.*

### RESULTS

- Results are concisely presented. The key findings are clear but because the figures only show effect size it’s not easy to get a feel for the data and its variability across sites and controls.

*Our goal is to report the effect of the reserve on the indicator, and using effect sizes allows us to reduce the ambiguity that temporal and spatial trends may induce. However, we recognize the importance of observing "raw" data, and have included time series of all indicators in the supplementary materials.*

- The presentation of governance information is brief. It seems that the purpose is to assess whether the characteristics of the system are conducive to effective local management of the resource, but this is not very informative given the depth of analysis – the same broad descriptions are presented for all three sites for many of the variables. I would question the value of this somewhat ‘tick box approach’ to SES systems across a small number of case studies. What are the questions driving this analysis and what does it add to the paper? It seems that much of this could be presented as a contextual summary of the study sites rather than as analysis.

*The interpretation is correct, we intend to provide enough information to show that the characteristics of the system are conductive of effective resource management. The reason why similar broad descriptions are presented across sites is because these don't vary across them. For example, all sites must align with the same official fisheries regulation (Lobster Fishery Official Mexican Norm; NOM-006-pesc-1993). Our end goal is to present the information as a contextual summary. The use of the SES framework simply allows us to be more objective by being transparent about the variables we report across communities and using a common language. We believe this is now made clear in sentence starting in L134.*

### DISCUSSION

- The key message seems to be that there are no significant changes in the species targeted for protection, nor other fishery-related species or fishery economic benefits. There are a number of plausible explanations presented that are all well established in the MPA literature (reserve size, duration, quality of existing fisheries management and environmental variability). While I appreciate the importance of publishing negative results in the MPA literature, it’s a shame that some of these factors weren't anticipated and explored in more detail.

- I found the second paragraph of the discussion difficult to follow – the key points here could be more clearly explained as they seem to point to the novelty of the statistical analysis.

*The main objective of this paragraph is to justify the use of our method, and highlight the advantages of using causal inference techniques. We have removed references to previous studies that used different methodologies because these distracted from the main point. We believe the paragraph now addresses three key messages: 1) There is a need for evidence-based conservation and the use of causal inference techniques, 2) Our study uses robust inference methods, which allow us to talk about the causal effect of reserve implementations, and 3) Provide a benchmark comparison by highlighting patterns that our analyses identifies and relate them to previously identified patterns.*

- The latter part of the discussion focuses on the additional potential benefits of reserves including the positive perceptions of fishers noted in another study. My view is that these benefits are over-emphasized here, given that there is no data in the manuscript to support them. Furthermore the potential counter-arguments (e.g. that resources invested in these reserves might be put to better use) are not considered, which leads to a fairly one-sided view.

*We believe that part of the disconnect had to do with the way in which the previous text was presented, where we failed to distinguish between the evaluated TURF-reserves, other non-evaluated TURF-reserves and other reserves not implemented within TURFs. We have also made it clear that some of the claims (which include citations) come from conclusions of other works performed on these same sites. For example, the buffering to environmental variation comes from Micheli et al., 2012, who evaluated the TURF-reserves in Isla Natividad.*

- It would be worth discussing fully the limitations of the data e.g. presumably the lack of data on fishing effort restricts interpretation of the time series, and the indicators representing socio-economic benefits of the MPAs are limited.

*We have included a paragraph on some of these limitations in the discussion (L271)*

### Is the quality of the figures and tables satisfactory?

- No

*Figures and table have been modified or added to the manuscript.*

#### Are the methods sufficiently documented to allow replication studies?

- No

*We have expanded on the methods and expect these to be now better documented.*

#### Are the data underlying the study available in either the article, supplement, or deposited in a repository? (Sequence/expression data, protein/molecule characterizations, annotations, and taxonomy data are required to be deposited in public repositories prior to publication) (yes/no/not applicable)

- No

*Our data and code are deposited in a public GitHub Repository. We have included a sentence in the methods sections mentioning this and a link to said repository (L201).*

\clearpage

# Reviewer 2

**Recommendation:** Moderate revisions

## Q1 - Please summarize the main findings of the study.

This paper assesses the effectiveness of 3 TURF-reserves using a Before-After-Control-Impact design. The results indicate that the reserves have not increased the density of targeted species. Besides the biological analysis, the authors also evaluate the social-ecological system at each study community based on selected indicators. They conclude that in order to maximize biological effectiveness, community-based TURF reserves need to have full community support as well as meet other reserve design criteria, such as appropriate size and location.

## Q2 - Please highlight the limitations and strengths.

Strengths: The study evaluates both the biological as well as social and governance system of marine reserves, which is not addressed simultaneously in many studies assessing marine reserve effectiveness.

Limitations:
The connection between the SES and biological evaluations need to be strengthened. At the same time, the SES provides a static picture of governance and resource conditions, whereas the biological assessment reflects changes through time. To bring these two components together, there is a need to provide information about how the SES has changed through time. Also the SES analysis lacks evaluation criteria. This inhibits a full picture of the combined biological and social contribution of TURF reserves. 

See further comments in Q3 below.

## Q3 - Please provide your detailed review report to the editor and authors (including any comments on the Q4 Check List):

- This paper assesses the effectiveness of 3 TURF-reserves using a Before-After-Control-Impact design. The results indicate that the reserves have not increased the density of targeted species. Besides the biological analysis, the authors also evaluate the social-ecological system at each study community based on selected indicators. While it is encouraging to see the authors consider the social and governance aspects of marine reserves, it appears that this is secondary to the biological assessment. As it is presented now, I don’t see the added insights that the SES analysis brings to the study. The effectiveness of reserves are primarily assessed based on the biological indicators only. This is due to the lack of evaluation criteria for the SES component. I’d suggest using some rating system to rate each of the SES indicators. E.g., for RS4.1 stock status – range of possible values would be overfished, underfished, etc. Where would each study site fall along the gradient of underfished to overfished stocks?

By doing this you can assess each site in terms of biological performance and SES conditions. This then allows you to establish a stronger connection on how biological and social factors together act to contribute to better protection and effectiveness of marine reserves. This to me, is where the study can make a contribution to the literature.

*The social evaluation is, indeed, secondary to this study. While we believe it is equally important, we assess reserve effectiveness based on the stated objectives, which were to increase lobster densities and landings. We incorporate the SES approach to provide more background about the system under which the reserves are placed, and to discard the usually-mentioned causes of lack of effectiveness which "blame" fishers (namely poaching and lack of enforcement). Instead, our approach shows that the most likely cause of lack of effectiveness is poor design, that ignore basic design principles such as size of reserves.*

- Further to my comment above, my understanding of this paper is that the authors are making an argument for TURF-reserves. However the rationale for this does not come out clearly in the paper. There needs to be stronger justification provided for why the authors expect the 18 TURF-reserves to perform better than i) non-TURF community based marine reserves, and ii) TURF fisheries (but not necessarily marine reserves). Without this clarification, there is nothing to distinguish this study from others which assess the fishery impacts of marine reserves.

*We believe that the re-structuring of the introduction and case study descriptions have now addressed this.*

- Does fishing occur inside the marine reserves, or outside the marine reserves? If the fishing occurs inside the marine reserve then please clarify that the marine reserves are NOT no-take marine reserves.

*No fishing activities occur within the Marine Reserves, and we have now made it clear that these are no-take marine reserves.*

- Were the fisheries at each study site managed as TURFs prior to the establishment of the marine reserves? 

*Yes, these fisheries have been historically managed with TURFs. We have included this in the case study description (sentence starting in L120).*

- L67. What is a triple bottom line evaluation of the effectiveness of community based marine reserves? Please clarify triple bottom line and what the criteria for this are.

*We were using the term "triple bottom line evaluation" in the same way as Halpern 2013 did. We realize that this is not clear, and have now explicitly stated that we "provide a holistic evaluation of the effectiveness of community-based in terms of the changes in biological and socioeconomic indicators and the governance settings under which these develop" (L65).*


### Methods

- Please provide the size of each of the reserves. Reserve size is an important factor affecting ecological outcomes, especially when comparing comparatively mobile vs non-mobile species (as noted by the authors in the Discussion). Why was the effect of reserve size not assessed? 

*The sizes were included in Table 2 (RS3 - Size of resource system: reserve area), but are now also mentioned in the results (L248). We do not directly assess the effect of reserve size because all reserves are smaller than the suggested design principles (Green et al., 2017). If we had data from more sites and across a wider range of reserve sizes (i.e. smaller and greater than minimum requirements) it would be interesting to show how time to recovery or effect sizes relate to reserve size. One would expect to find a positive correlation.*

- Are the control sites managed with TURFs even though they are non-reserves? 

*Yes, all control sites are placed within the TURFs, as it is now explicitly mentioned in the case study section (list starting in L141).*

The socioeconomic analysis needs to address these points:

- Provide the ex-vessel prices of lobster and invertebrates at each study site.

*Mean ex-vessel prices for lobster are now presented in Table S3*

- Did you control for difference in prices between sites?

*Yes, our Difference-in-Differences analyses controls for community-specific changes.*

- Would observed differences in revenue inside/outside reserves be due to difference in landings or due to price differences?

*Differences in revenue may be explained by both, a simple increase in prices due to market interactions or an increase in landings (plausibly because of the reserve). However, we do not observe an increase in revenues nor in landings, and ex-vessel prices remain relatively constant.*

### Results

- Please provide results for biological and socioeconomic indicators - Average density/biomass, landings and revenue for lobster, invertebrates and fish by year in and outside marine reserves (control sites). If space is an issue then include these results in the Supplementary Materials. 

*These were also requested by Reviewer #1 and have now been included in the Supplementary Materials.*

- What was the species and community effect on biological and socioeconomic indicators, respectively?

*We did not directly evaluate the community- or species-level effects on the indicators. Since we fit one model for each combination of indicator-community, we cannot make inference about the community- or species-level effects. This type of analyses would be more suited for a community ecology approach, or when seeking differential response among species (e.g. Babcock et al, 2010). Furthermore, we believe that this approach should be used in a post hoc fashion for reserves that have actually had an effect on the indicators, seeking to understand which species and communities may be driving this.*

#### Table 2: Some variables need further clarification.

- RU5 – Number of targeted species is the variable, but this isn't specified in the narrative. In addition to noting that lobster is the main target species please enter the total number of targeted species.

*We have included the total number of species targeted*

- A1 – Number of fishers. I assume that the numbers listed refer only to the number of fishing co-op members. Are there other non-coop fishers in the fishing communities? If yes, what is the ratio of co-op to non co-op fishers? The point of this question is to see how the benefits of TURFs are distributed among the entire community, not just within the fishing co-op.

*This assumption is correct, we only list the number of fishing co-op members. However, all fishers that fish within the TURF belong to the cooperative, and there are no "free fishers". This point is now mentioned in the case study section (L90).*

- A3 – Level of isolation. The narrative says that fishing grounds and reserves are away from dense urban centers – can you provide the distance from each study site to the nearest urban center (km).

*We have included the linear distance to the closes urban centers in Table 2. Isla Natividad lies 545 Km south from Tijuana, while Maria Elena and Punta Herrero are more than 200 km south from Cancun.*

- GS6.2 Which rules (larger min catch size, lower quotas etc) pertain to each site?

*All rules are applied for all sites. We have changed the wording from "these include" to "these are" in Table 2.*

- GS9.1 Social monitoring – Do fishing coops at all 3 sites have the same monitoring and enforcement regime in place?

*Yes, they have the same regime known as "Consejo de vigilancia". We have now included this particular wording in Table 2.*

- GS9.2 Biophysical monitoring – Are all the listed monitoring activities performed at all 3 sites?

*Yes, each community engages in biological monitoring (the data for this study comes from this) and oceanographic monitoring.*

- GS 10.1 Graduated sanctions – Again, which of the penalties are relevant to each site?

*The sanctions and penalties are homogeneous across sites. However, sanctions are administered on a case-by-case basis and voted or agreed by all cooperative members before being applied.*

- As it is presented now, the governance variables are a bit unclear as to which type of rules/regulations are practiced at each of the three sites. I recognize that this is because these variables are more qualitative in nature. However to make it clearer, the Narrative column could be split into 3 - one column per study site, and the relevant information entered under each site column.

*We believe that splitting the narrative column into three would be beneficial if each community had very different values / narratives. However, these three communities have strikingly similar values. Splitting it into three columns would result in redundant text being repeated across columns. However, we do understand the point that it is difficult to recognize which values correspond to each community. To address this, we have modified the table caption to explain that the values apply to all communities, and when needed a specific community-level narrative is included (for example, isolation of IN vs PH and ME).*

- Table 2. As per my comment about rating the SES indicators, add a column in between the “Variable” and “Narrative” column to describe the range of potential values/conditions for each “Variable”. E.g., for Governance system Social monitoring can range from “Strong” to “Weak”. You could attach points to a gradient of “Strong” to “Weak” to produce a quantitative assessment, or enter a qualitative assessment. Then each site will either be assessed with points or a qualitative descriptor. The main point is to provide the reader with a better sense of what a “strong” or “weak” governance system looks like, and where each site falls along this gradient. This is missing from the current table.

*This is a fair point, which was raised previously. This would be an interesting approach. Initially, we had "operationalized" the SES framework and included a scoring system. However, since all sites operate under very similar settings scores were practically the same and obtained little contrast between them. We believe that this happens because the three communities represent well-managed fisheries, and all of them achieve high scores. The approach suggested would be much more interesting if it could be applied to a series of fisheries along a wider gradient of cooperation and co-management. We have included a discussion paragraph recognizing this (L330).*

- Fig 2B and 2D. Why are there big fluctuations in fish biomass from Years 7-10, but density stays pretty much the same for the same time period?

*This big fluctuations in biomass are explained by an opportunistic increase in sizes. In this particular case, a few larger-than-usual organisms were observed, but the total number of fish remained similar to other years. As a result, the few larger fish observed these years yield a higher biomass. However these differences are not significantly different from the pre-observed trend.*

### Discussion

- L238-240: “Our analysis of economic data supports this hypothesis….reserve implementation”. I don’t understand what the authors are trying to convey in this sentence. What are the expected short-term costs associated to the first years of reserve implementation? Please clarify. 

*After the first few years of reserve implementation, one would expect landings to decrease. This would be explained by the relative reduction of total fishable area. The "dip" described in Ovando et al., (2016) would then recover as densities inside the reserve recover and spillover occurs. The fact that we don't see a reduction in landings over the first few years suggests that reserves are not big enough to reduce landings over the first few years.*

- L208-209 – The authors state that “Understanding the socio-ecological context... provide insights as to why this happens”, but then don’t provide further elaboration. The reader is not getting any insight as to why the communities continue to support the reserves. Even though this is presumably covered in the provided reference to Ayer et al. 2018 a brief explanation is required here. Please add this to the Discussion.

*This lose statement has been removed after the re-structuring the discussion.*

- Clearly state the lessons learned. L274 simply says that “Lessons learned from these cases can guide implementation…” But what are these lessons?

*We have removed this lose statement and included an explicit conclusions paragraph (L335) where we state that "We must promote bottom-up design and implementation processes like the ones in the evaluated reserves, but without setting design principles aside".*

- L277 the authors state that “Community-based marine reserves might have more benefits…” Are the authors referring to the reserves assessed in this study, or to community based marine reserves in general? If referring to this study, the conclusion is not supported by the results, as the authors did not compare community-based to non-community based reserves. Need to clarify this point.

*The previous wording of this statement was confusing, and seemed like we were referencing the reserves evaluated in this work. Clearly this is not true and our data would not support such claim. As with previous statements, we believe this is now clear after re-structuring the discussion.*

- L268-269 “Furthermore, the lack of effectiveness observed in these reserves should not be generalizable to other reserves established under the same legal framework”. This appear to contradict L99-100 which says that “it is safe to cautiously generalize our insights to other similar reserves…”

*Similar points were raised by Reviewer #1. We believe our current wording and expansion of study sites now makes clear when we refer to the evaluated TURF-reserves, other TURF-reserves and other reserves outside TURFs. This same idea that other reserves may be effective is now shown in a new paragraph (L330).*

- L196. “…the benefits of conservation directly benefit the members of the fishing cooperatives…” But what about benefits to the community as a whole? Going back to my question about number of actors in Table 2 – I assume that the invertebrate fisheries are high value fisheries. As such, it’s important to consider how the benefits of TURF-reserves are distributed among the entire community. Please provide some discussion about the distribution of fishery benefits – do the number of TURF fishers make up only a small proportion of total active fishers in the community? Or are all fishers in each community able to participate in the TURFs?

*The expansion of the study sites and description of Communities / TURFs / Fisheries in these areas may now provide more context to avoid confusion.*

- The Discussion is focused mainly on ecological factors which may have affected the effectiveness of the TURF-reserves. What about potential changes in social-economic and governance conditions over the assessed time period which may have affected the reserve? For instance was there a breakdown in enforcement which may have led to illegal fishing, thereby resulting in lower density of target species? What about market drivers that may have motivated increased fishing pressure? Elaboration on these factors will strengthen the authors’ attempt to bring in the SES framework to this primarily biological analysis. 

*Our SES approach is intended to provide a snapshot of the state of each community. We do not include time-varying values for any indicator because all these have remained constant at least since reserve implementation. The only addition to their community-based management have been the biological and oceanographic monitoring (GS9.2) which started at least one year before reserve implementation. As per market drivers that may increase fishing pressure, our supplementary materials show little change in prices before / after the implementation of the reserves, and it is unlikely that TURF-managed fisheries (plausibly managed at optimum) would deviate from this already optimal management point. However, we believe some of these points have now been covered in our discussion (L271).*

### Minor comments:

Figure 2 caption: first line (IN; red circles) “circles” is spelled wrong. 

*The figure caption has been corrected and now says "circles"*

place-holder

*This would be an interesting approach. Initially, we had "operationalized" the SES framework and included a scoring system. However, since all sites operate under very similar settings scores were practically the same and obtained little contrast between them. We believe that this happens because the three communities represent well-managed fisheries, and all of them achieve high scores. The approach suggested would be much more interesting if it could be applied to a series of fisheries along a wider gradient of cooperation and co-management. We have included a discussion paragraph recognizing this (L330).*


