---
title: "Effectiveness of community-based TURF-reserves in Mexican small-scale fisheries"
output:
  bookdown::pdf_document2:
    keep_tex: yes
    template: template_sup.tex
---

Raw data and code are available on GitHub at: [https://github.com/jcvdav/ReserveEffect](https://github.com/jcvdav/ReserveEffect)

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

options(knitr.table.format = "latex")
```

```{r, eval = T}
suppressPackageStartupMessages({
  library(magrittr)
  library(tidyverse)
})
```

```{r load_data, eval = T}
invert <- read.csv(file = here::here("data", "invertebrates.csv"),
                stringsAsFactors = F) %>% 
  mutate(zona = ifelse(zona == "Reserva", "Reserve", zona))

fish <- read.csv(file = here::here("data", "fish.csv"),
                stringsAsFactors = F) %>% 
  mutate(zona = ifelse(zona == "Reserva", "Reserve", zona))

conapesca <- read.csv(file = here::here("data", "conapesca.csv"),
                stringsAsFactors = F) %>% 
  mutate(zona = ifelse(zona == "Reserva", "Reserve", zona))
```

```{r eval = T}
invert %>% 
  group_by(ano, comunidad, zona, sitio, transecto) %>%
  count() %>% 
  ungroup() %>% 
  group_by(comunidad, zona) %>%
  count() %>% 
  ungroup() %>% 
  spread(zona, nn) %>% 
  mutate(age = c(10, 4, 4)) %>% 
  knitr::kable(caption = "Number of invertebrate transects performed in each site of each community.",
               col.names = c("Community", "Control", "Reserve", "Years of monitoring"),
               booktabs = T)
```

```{r, eval = T, fig.cap = "Time series of lobster densities. Bars indicate standard errors."}
invert %>%
  mutate(generoespecie = ifelse(generoespecie %in% c("Panulirus interruptus", "Panulirus argus"),
                             generoespecie,
                             "any_invert")) %>% 
  group_by(rc, ano, year, comunidad, sitio, zona, transecto, generoespecie) %>% 
  summarize(abundancia = sum(abundancia)) %>% 
  spread(generoespecie, abundancia, fill = 0) %>% 
  gather(generoespecie, abundancia, -c(rc, ano, year, comunidad, sitio, zona, transecto)) %>% 
  filter(generoespecie %in% c("Panulirus interruptus","Panulirus argus")) %>% 
  group_by(rc, ano, year, comunidad, sitio, zona, transecto, generoespecie) %>% 
  summarize(indicador = sum(abundancia)/60) %>%
  ungroup() %>% 
  mutate(year = as.numeric(year)) %>% 
  ggplot(aes(x = year, y = indicador, color = zona)) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.1, size = 1) +
  stat_summary(geom = "line", fun.y = mean) +
  stat_summary(geom = "point", fun.y = mean, size = 2) +
  theme_minimal() +
  facet_wrap(~comunidad, scales = "free", ncol = 2) +
  scale_color_brewer(palette = "Set1", direction = -1) +
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylab(bquote("Density (org m"^{-2}~")")) +
  xlab("Year since implementation") +
  theme(legend.justification = c(0,0),
        legend.position = c(0.5, 0.15)) +
  guides(color = guide_legend(title = "Zone"))
```


```{r, fig.cap = "Time series of invertebrate densities. Bars indicate standard errors."}
invert %>%
  filter(abundancia > 0) %>%
  group_by(rc, ano, year, comunidad, sitio, zona, transecto, generoespecie) %>% 
  summarize(indicador = sum(abundancia)/60) %>%
  ungroup() %>% 
  mutate(year = as.numeric(year)) %>% 
  ggplot(aes(x = year, y = indicador, color = zona)) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.1, size = 1) +
  stat_summary(geom = "line", fun.y = mean) +
  stat_summary(geom = "point", fun.y = mean, size = 2) +
  theme_minimal() +
  facet_wrap(~comunidad, scales = "free", ncol = 2) +
  scale_color_brewer(palette = "Set1", direction = -1) +
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylab(bquote("Density (org m"^{-2}~")")) +
  xlab("Year since implementation") +
  theme(legend.justification = c(0,0),
        legend.position = c(0.5, 0.15)) +
  guides(color = guide_legend(title = "Zone"))
```

\clearpage

```{r}
fish %>% 
  group_by(ano, comunidad, zona, sitio, transecto) %>%
  count() %>% 
  ungroup() %>% 
  group_by(comunidad, zona) %>%
  count() %>% 
  ungroup() %>% 
  spread(zona, nn) %>% 
  mutate(age = c(10, 4, 4)) %>% 
  knitr::kable(caption = "Number of invertebrate transects performed in each site of each community.",
               col.names = c("Community", "Control", "Reserve", "Years of monitoring"),
               booktabs = T)
```

```{r, fig.cap = "Time series of fish biomass. Bars indicate standard errors."}
fish %>%
  filter(abundancia > 0) %>% 
  group_by(rc, ano, year, comunidad, sitio, zona, transecto, generoespecie, talla, a, b) %>% 
  summarize(abundancia = sum(abundancia)) %>% 
  ungroup() %>% 
  mutate(year = as.numeric(year),
         biomass = abundancia * ((a * (talla^b))/1000))  %>% 
  ggplot(aes(x = year, y = biomass, color = zona)) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.1, size = 1) +
  stat_summary(geom = "line", fun.y = mean) +
  stat_summary(geom = "point", fun.y = mean, size = 2) +
  theme_minimal() +
  facet_wrap(~comunidad, scales = "free", ncol = 2) +
  scale_color_brewer(palette = "Set1", direction = -1) +
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylab(bquote("Biomass (Kg m"^{-2}~")")) +
  xlab("Year since implementation") +
  theme(legend.justification = c(0,0),
        legend.position = c(0.5, 0.15)) +
  guides(color = guide_legend(title = "Zone"))

```

\clearpage

```{r, fig.cap = "Time series of fish densities. Bars indicate standard errors."}
fish %>%
  group_by(rc, ano, year, comunidad, sitio, zona, transecto, generoespecie) %>% 
  summarize(indicador = sum(abundancia)/60) %>%
  ungroup() %>% 
  mutate(year = as.numeric(year)) %>% 
  ggplot(aes(x = year, y = indicador, color = zona)) +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.1, size = 1) +
  stat_summary(geom = "line", fun.y = mean) +
  stat_summary(geom = "point", fun.y = mean, size = 2) +
  theme_minimal() +
  facet_wrap(~comunidad, scales = "free", ncol = 2) +
  scale_color_brewer(palette = "Set1", direction = -1) +
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylab(bquote("Density (org m"^{-2}~")")) +
  xlab("Year since implementation") +
  theme(legend.justification = c(0,0),
        legend.position = c(0.5, 0.15)) +
  guides(color = guide_legend(title = "Zone"))
```

\clearpage

```{r}
conapesca %>% 
  filter(!unidad_economica == "jose maria azcorra") %>% 
  mutate(price = valor / peso_vivo) %>% 
  group_by(zona, grupo, post, unidad_economica) %>% 
  summarize(price = mean(price, na.rm = T)) %>% 
  ungroup() %>% 
  spread(post, price) %>% 
  mutate(zona = ifelse(zona == "MC", "Yucatan Peninsula", "Baja California"),
         unidad_economica = taxize::taxize_capwords(unidad_economica)) %>% 
  knitr::kable(digits = 2,
               col.names = c("Community", "Group", "TURF", "Before", "After"),
               caption = "Mean ex-vessel prices (MXP / Kg) for lobster (Panulirus spp.) on each TURF (community) and group (Control = only TURF, Treated = TURF and reserve).",
               booktabs = T)
```

```{r, fig.cap = "Time series of landings and value of landings."}
valor <- conapesca %>% 
  filter(!unidad_economica == "jose maria azcorra") %>% 
  mutate(zona = ifelse(zona == "MC", "Yucatan Peninsula", "Baja California")) %>% 
  ggplot(aes(x = years_centered, y = valor / 1000, color = grupo)) +
  facet_wrap(~ zona, ncol = 2, scales = "free_y")  +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.1, size = 1) +
  stat_summary(geom = "line", fun.y = mean) +
  stat_summary(geom = "point", fun.y = mean, size = 2) +
  theme_minimal() +
  scale_color_brewer(palette = "Set1", direction = -1) +
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylab("Value (K MXP)") +
  xlab("") +
  guides(color = guide_legend(title = "", ncol = 2)) +
  theme(legend.justification = c(0,0),
        legend.position = c(0.55, 0.7)) +
  geom_vline(xintercept = 0, linetype = "dashed", size = 1)

peso <- conapesca %>% 
  filter(!unidad_economica == "jose maria azcorra") %>% 
  ggplot(aes(x = years_centered, y = peso_vivo / 1000, color = grupo)) +
  facet_wrap(~ zona, ncol = 2, scales = "free_y")  +
  stat_summary(geom = "errorbar", fun.data = mean_se, width = 0.1, size = 1) +
  stat_summary(geom = "line", fun.y = mean) +
  stat_summary(geom = "point", fun.y = mean, size = 2) +
  theme_minimal() +
  scale_color_brewer(palette = "Set1", direction = -1) +
  scale_fill_brewer(palette = "Set1", direction = -1) +
  ylab("Landings (Tones)") +
  xlab("Year since implementation") +
  theme(legend.position = "none") +
  geom_vline(xintercept = 0, linetype = "dashed", size = 1)

cowplot::plot_grid(peso, valor, ncol = 1)
  
```

\clearpage

```{r}
load(here::here("data", "results", "results.RData"))
```

```{r}
supp_regtable <- function(models, caption = "", fs = "tiny", bio = T){
  
  labels <- c(
    "Lobster abundance",
    "Fish biomass",
    "Invertebrate abundance",
    "Invertebrate biomass")
  
  if(!bio){
    labels <- c(
      "Landings",
      "Revenues")
  }
  
  stargazer::stargazer(models,
                     omit = c(
                       "generoespecie",
                       "unidad"),
                     se = commarobust::makerobustseslist(models, type = "HC1"),
                     t.auto = T,
                     p.auto = T,
                     column.labels = labels,
                     dep.var.labels = "",
                     single.row = T,
                     omit.stat = c("f", "adj.rsq"),
                     title = caption,
                     header = F,
                     font.size = fs,
                     column.sep.width = "1pt")
}
```

```{r, results = "asis"}
list(L_IN, B_IN, Ni_IN, N_IN) %>% 
  supp_regtable(caption = "Coefficient estimates of biological indicators for Isla Natividad.")
```

\clearpage

```{r, results = "asis"}
list(L_ME, B_ME, Ni_ME, N_ME) %>% 
  supp_regtable(caption = "Coefficient estimates of biological indicators for Maria Elena.")
```

\clearpage

```{r, results = "asis"}
list(L_PH, B_PH, Ni_PH, N_PH) %>% 
  supp_regtable(caption = "Coefficient estimates of biological indicators for Punta Herrero.",
                fs = "small")
```

\clearpage

```{r, results = "asis"}
list(C_IN, V_IN) %>% 
  supp_regtable(caption = "Coefficient estimates of socioeconomic indicators Isla Natividad.",
                bio = F)
```

\clearpage

```{r, results = "asis"}
list(C_ME, V_ME) %>% 
  supp_regtable(caption = "Coefficient estimates of socioeconomic indicators for Maria Elena.",
                bio = F)
```

